version: '3.8'
services:
  api:
    build: .
    container_name: nestjs-sandbox-api
    ports:
      - '3300:3000'
    env_file:
      - .env
    volumes:
      - .:/usr/src/app   # live‑reload during development
    command: sh -c "npm install && npm run start:dev"

  # Example stub for a database (Postgres) if you want one later:
  db:
    image: postgres:15-alpine
    container_name: nestjs-sandbox-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sandbox
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
